name: "Detect changes"
description: "Decide what steps need running based on changes"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
runs:
  using: "composite"
  steps:
    - id: actionlint
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          .github/*/**.yml
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: prettier
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          **.md
          **.yml
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: compare-changes-action
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          .release/compare-changes-action/**
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: find-changes-action
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          .release/find-changes-action/**
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: homebrew-tap
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          .release/homebrew-tap/**
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: github
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          .release/archive.sh
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: nix
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          .release/nur-packages/**
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: rs
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          **.rs
          Cargo.lock
          Cargo.toml
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: rust
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          .cargo/**
          src/**
          tests/**
          Cargo.lock
          Cargo.toml
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: shellcheck
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        workflow: wildcard/shellcheck.yml
        changes: ${{ inputs.changes }}
    - id: src
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          src/**
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: zensical
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          docs/**
          zensical.toml
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
    - id: zizmor
      uses: anttiharju/compare-changes-action@v0.12.19
      with:
        paths: |
          **/action.yml
          .github/workflows/*.yml
          flake.lock
          flake.nix
        changes: ${{ inputs.changes }}
outputs:
  actionlint:
    description: "Whether actionlint has changed"
    value: ${{ steps.actionlint.outputs.changed }}
  prettier:
    description: "Whether Prettier has changed"
    value: ${{ steps.prettier.outputs.changed }}
  compare-changes-action:
    description: "Whether compare-changes-action has changed"
    value: ${{ steps.compare-changes-action.outputs.changed }}
  find-changes-action:
    description: "Whether find-changes-action has changed"
    value: ${{ steps.find-changes-action.outputs.changed }}
  homebrew-tap:
    description: "Whether homebrew-tap has changed"
    value: ${{ steps.homebrew-tap.outputs.changed }}
  github:
    description: "Whether GitHub has changed"
    value: ${{ steps.github.outputs.changed }}
  nix:
    description: "Whether Nix has changed"
    value: ${{ steps.nix.outputs.changed }}
  rs:
    description: "Whether *.rs has changed"
    value: ${{ steps.rs.outputs.changed }}
  rust:
    description: "Whether Rust has changed"
    value: ${{ steps.rust.outputs.changed }}
  shellcheck:
    description: "Whether ShellCheck has changed"
    value: ${{ steps.shellcheck.outputs.changed }}
  src:
    description: "Whether src has changed"
    value: ${{ steps.src.outputs.changed }}
  zensical:
    description: "Whether Zensical has changed"
    value: ${{ steps.zensical.outputs.changed }}
  zizmor:
    description: "Whether Zizmor has changed"
    value: ${{ steps.zizmor.outputs.changed }}

  release:
    description: "Whether any release has changed"
    value: ${{ steps.compare-changes-action.outputs.changed || steps.find-changes-action.outputs.changed || steps.homebrew-tap.outputs.changed || steps.github.outputs.changed || steps.nix.outputs.changed }}
